-- Create system tables
CREATE TABLE IF NOT EXISTS
    USERINFO
    (
        ID BIGINT NOT NULL IDENTITY,
        EMAIL VARCHAR(255),
        LOGIN VARCHAR(255),
        MOBILEDEVICEKEY CLOB,
        PASSWORD CLOB,
        REGISTRATIONID CLOB,
        USERTYPE INTEGER,
        PRIMARY KEY (ID),
        UNIQUE (LOGIN)
    );
CREATE TABLE IF NOT EXISTS
    MESSAGE
    (
        ID BIGINT NOT NULL IDENTITY,
        MESSAGE CLOB,
        WASREAD BOOLEAN,
        FROM_ID BIGINT,
        TO_ID BIGINT,
        PRIMARY KEY (ID),
        CONSTRAINT FK9C2397E768E45D2B FOREIGN KEY (FROM_ID) REFERENCES USERINFO (ID) ON
    DELETE
        RESTRICT,
        CONSTRAINT FK9C2397E792E7A8BA FOREIGN KEY (TO_ID) REFERENCES USERINFO (ID)
    ON
    DELETE
        RESTRICT
    );
CREATE TABLE IF NOT EXISTS
    SERVERCONFIG
    (
        KEY VARCHAR(255) NOT NULL,
        VALUE VARCHAR(255),
        PRIMARY KEY (KEY)
    );
