
-- drop tables
DROP TABLE IF EXISTS MESSAGE;
DROP TABLE IF EXISTS SERVERCONFIG;
DROP TABLE IF EXISTS USERINFO;

-- create tables
CREATE TABLE USERINFO (ID BIGINT NOT NULL IDENTITY, EMAIL VARCHAR(255), LOGIN VARCHAR(255), MOBILEDEVICEKEY CLOB, PASSWORD CLOB, REGISTRATIONID CLOB, USERTYPE INTEGER, PRIMARY KEY (ID), UNIQUE (LOGIN));
CREATE TABLE MESSAGE (ID BIGINT NOT NULL IDENTITY, MESSAGE CLOB, FROM_ID BIGINT, TO_ID BIGINT, PRIMARY KEY (ID), CONSTRAINT FK9C2397E768E45D2B FOREIGN KEY (FROM_ID) REFERENCES USERINFO (ID) ON DELETE RESTRICT, CONSTRAINT FK9C2397E792E7A8BA FOREIGN KEY (TO_ID) REFERENCES USERINFO (ID) ON DELETE RESTRICT);
CREATE TABLE SERVERCONFIG (KEY VARCHAR(255) NOT NULL, VALUE VARCHAR(255), PRIMARY KEY (KEY));

-- insert users
INSERT INTO USERINFO (ID, EMAIL, LOGIN, MOBILEDEVICEKEY, PASSWORD, REGISTRATIONID, USERTYPE) VALUES (1, 'admin@mailinator.com', 'admin', 'ea79ddb79a49dad6ae43c171ac96649d273f1a23f6824452e33add6cdc94deb', '�e�Y B/�A~Hg��O��J?��~������z�', null, 0);
INSERT INTO USERINFO (ID, EMAIL, LOGIN, MOBILEDEVICEKEY, PASSWORD, REGISTRATIONID, USERTYPE) VALUES (2, 'eldius@mailinator.com', 'eldius', 'c6b282caa99e4a912a6f718555a3e943696db0de290d9ce9e923e20d352ac81', '�e�Y B/�A~Hg��O��J?��~������z�', null, 1);
INSERT INTO USERINFO (ID, EMAIL, LOGIN, MOBILEDEVICEKEY, PASSWORD, REGISTRATIONID, USERTYPE) VALUES (3, 'usuario01@mailinator.com', 'usuario01', null, '�e�Y B/�A~Hg��O��J?��~������z�', null, 1);

-- insert app configs
INSERT INTO SERVERCONFIG (KEY, VALUE) VALUES ('app.config.open_reg', 'true');

-- insert messages
INSERT INTO MESSAGE (ID, MESSAGE, FROM_ID, TO_ID) VALUES (7, 'Hi there!', 2, 1);
INSERT INTO MESSAGE (ID, MESSAGE, FROM_ID, TO_ID) VALUES (8, 'Hi dude, whatsapp?', 2, 2);
INSERT INTO MESSAGE (ID, MESSAGE, FROM_ID, TO_ID) VALUES (9, 'I''m good...', 2, 1);
INSERT INTO MESSAGE (ID, MESSAGE, FROM_ID, TO_ID) VALUES (10, 'And you?', 2, 1);
INSERT INTO MESSAGE (ID, MESSAGE, FROM_ID, TO_ID) VALUES (11, 'I''m fine too...', 2, 2);

